### ISSUE TITLE
Error Management

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [flint-bot/sparky#10]
When the Cisco Spark API returns an error such as a 409, I am having difficulties handling it from my client application code.

Sparky returns an err containing only a message, which gives no other option but to do string comparison, or creating a regexp to matching a 409 status error.

**Comment by ObjectIsAdvantag** [comment]
Here is an example of strategy to handle the error with current version of sparky:

```javascript
sparky.membershipAdd(roomId, personEmail, false)
.then(function (membership) {
   ...
})
.catch(function (err) {
   var hasHttpStatusCode = err.message.match(/recieved error (\d{3}) for a POST request/);
   if (hasHttpStatusCode && (hasHttpStatusCode[1] == "409")) {
      // user is already in space
   }
}
```

**Comment by ObjectIsAdvantag** [comment]
It seems that sparky may encounter 3 main types of issues while requesting Cisco Spark APIs:
- HTTP request establishment: timeout, ...
- HTTP response format issues: unexpected payload 
- HTTP responses with a non 2xx status code: something went wrong 4xx or 5xx series

A possible design could be to add extra info to the Error object:
- err.type = ERR_REQUEST, ERR_RESPONSE or ERR_STATUS
- and in case of ERR_STATUS, we would also add a err.statusCode with the value returned by CiscoSpark.

**Comment by nmarus** [comment]
[This](https://github.com/flint-bot/sparky/blob/f35c312a6b8a19f5373829322baa2d48660d9358/lib/spark.js#L297-L301) should be the function that is needed to modify the scope of the returned error object as per your suggestions above. 

Something like:

```javascript
const processError = (_res, _opts) => {
  const err = new Error(`recieved error ${_res.statusCode} for a ${_opts.method.toUpperCase()} request to ${_opts.url}`);
  // attach statusCode to error
  err.code = _res.statusCode;
  if (parseInt(_res.statusCode, 10) === 409) {
    err.type = 'ERR_REQUEST';
  } else if (parseInt(_res.statusCode, 10) === 123)
   err.type = 'ERR_BLAH';
  // other conditions...
  } else {
   err.type = 'ERR_STATUS';
  } 
  console.error(err);
  return when.reject(err);
};
```

Feel free to do a PR or let me know know thoughts on above and which statusCodes you think should map to what types and I can make this change this weekend.

**Comment by nmarus** [comment]
Addressed in v.4.2.0

**Comment by ObjectIsAdvantag** [comment]
Excellent !!! thanks @nmarus
