### ISSUE TITLE
need a getMessagesAfter function

### ISSUE THREAD

**Issue by nacklebert** [flint-bot/sparky#11]
Spark APIs do not provide a way to get/list messages for a space _after_ a certain date, only before... 
 that isnt very helpful in many situations.  The /events API is only available to compliance officer roles, which is not the vast majority of users.  We need a way, with a standard user token (from oAuth) to list messages from a certain date till now...  Ideally sparky would fill that void with a getMessagesAfter(date, roomId, pagesize) could go back page-by-page till it finds the the threshold message/time.

**Comment by nmarus** [comment]
Try v4.3.0, added a 'after' property that can be used in the search object of messagesGet(). Might not be very efficient yet, but wil see what I can do to enhance that with some further testing.

**Comment by nmarus** [comment]
Example:

```js
const Spark = require('node-sparky');
const token = 'sometoken';
const roomId = 'someroomid';

const spark = new Spark({ token });

spark.messagesGet({ roomId: roomId, after: '2017-12-23T00:00:00.000Z' })
  .then(messages => messages.forEach(message => console.log(`${message.created} ${message.text}`)));
```
