### ISSUE TITLE
Addition of Admin API?

### ISSUE THREAD

**Issue by darrenparkinson** [flint-bot/sparky#4]
Hi Nick,

Are there any plans to add the [Admin API](https://developer.ciscospark.com/admin-api.html)?

Thanks.

**Comment by nmarus** [comment]
Yes. Just haven't added them yet. It's on the backlog. :)

**Comment by darrenparkinson** [comment]
No problem.  I've started [a new branch](https://github.com/darrenparkinson/sparky/tree/issue-4) and have added the below so far.  I've tried to match the existing code as much as possible in the hope you might accept it as a PR ;).

* organizationsGet
* organizationGet
* licensesGet
* licenseGet
* rolesGet
* roleGet
* personAdd

I wanted to ask you about [updating a person](https://developer.ciscospark.com/endpoint-people-personId-put.html) though since for most of the update (PUT) functions, you've used friendly function names like `roomRename` and `membershipSetModerator`.  

I wondered how you might add the update person functions in this case?  For example, would you just add a single `updatePerson` function or would you split it out into `changePersonAvatar` and similar?

Any thoughts you have greatly appreciated.  Thanks.
D.

**Comment by nmarus** [comment]
Thanks for contributing. Got ahead and do a PR when you are ready. 

In regard PUT/update, I've been thinking about that as well. I had a case open with dev team for Spark API to ask about some inconsistent ways they had implemented PUT between various API calls. Seems to be fixed to be consistent now and I got the response:

> The HTTP PUT request assumes the body of the resource is given in its entirety. However, when using a PUT request a partial update is not supported. If a required attribute is not given, it will instead return an error. In comparison, if an optional attribute is given, we nullify it. Instead of using a PUT request you will want to do a GET request of the resource and then modify the fields that you would like and feed that into the PUT request.

With that, I'd say the update for a person should have the same params as the insert (POST) for a person. I'm probably (unless you want to) going to write in functions for the other resources (room/membership/etc) to do the same with the friendlies either getting deprecated or perhaps going the route of having friendlies along with the full object update. /unsure

**Comment by darrenparkinson** [comment]
Thanks.  Yes, I'd noticed there was an inconsistency there too.  That makes sense.  I've added an update function and a delete function now too.  Just a quick question on the docs before I create the PR -- do you have an automated process for creating them, or should I manually update the readme.md?

**Comment by nmarus** [comment]
You can rebuild the README.md (assuming you are on linux/mac/etc bash CLI) if you wish by doing the following from the project dir:

```bash
npm install
cd docs
./build.sh
```

Else I can do this before I update the npm. Either way.

**Comment by nmarus** [comment]
@darrenparkinson Thanks for the PR. I modified the personAdd and personUpdate methods to accept an object instead of a list of arguments. It makes optional arguments easier to handle. Let me know what you think. I also re-ordered the functions for the documentation generator. I have not pushed to npm yet as I still need to do some testing.

**Comment by darrenparkinson** [comment]
It's funny you should say both of those things. When I was creating the functions I thought passing an object would be better. Especially given that so many arguments need passing in.  I also wondered if I should move them around for the documentation too but decided to leave all the new bits together... Definitely happy with the changes.
