### ISSUE TITLE
messagesGet validator issue

### ISSUE THREAD

**Issue by glebretonoab** [flint-bot/sparky#9]
I think i have an issue with isMessageSearch validator method 
`Validator.isMessageSearch = searchObj => (typeof messageSearch === 'object' && searchObj.roomId);`

This method test typeof "messageSearch" variable instead of "searchObj" variable.

Write like that, it works better.
`Validator.isMessageSearch = searchObj => (typeof searchObj=== 'object' && searchObj.roomId);`

**Comment by nmarus** [comment]
Thanks! Fix applied in v4.1.9.
